[package]
name = "leshy-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
memmap = "0.7.0"
leb128 = "0.2.5"
lazycell = "1.3.0"
