[package]
name = "leshy-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leb128 = "0.2.5"
lazycell = "1.3.0"
dynasm = "1.2.1"
dynasmrt = "1.2.1"
libc = "0.2"